### PR TITLE
ES384

### PR DESCRIPTION
**Pull request by IsraelZeromski**
Add P384 cryptography algorithm

### CODE REVIEW

**Comment by jedisct1** [comment]
Can you update the documentations as well, so that other users know that it exists?

**Comment by IsraelZeromski** [comment]
I updated readme adding ES384 elliptic curve JWT algorithm

**Comment by jedisct1** [comment]
`src/lib.rs` also needs an update :)

**Comment by jedisct1** [comment]
Oh, that was done. Sorry for overlooking that.

Thank you for contributing this!

**Pull request merged**
